import { describe, it, expect, vi } from "vitest";
import { Effect, Layer, Stream, Context } from "effect";
import { HaloOptimizerLive, HaloOptimizerService } from "./HaloOptimizerService.ts";
import { OrchestrationEventStore } from "../../persistence/Services/OrchestrationEventStore.ts";
import { EmbeddingProvider } from "./EmbeddingProvider.ts";
import * as SqlClient from "effect/unstable/sql/SqlClient";

// Mock the global fetch to simulate Ollama's response
global.fetch = vi.fn().mockResolvedValue({
  ok: true,
  json: async () => ({
    response: "NUGGET: Test Nugget generated by local HALO."
  })
} as unknown as Response);

describe("HaloOptimizerService", () => {
  it("should process traces and synthesize a local nugget natively", async () => {
    
    const MockEventStoreLive = Layer.succeed(OrchestrationEventStore, {
      readAll: () => Stream.make(
        { type: "thread.message.user", commandId: "c1", threadId: "t1", occurredAt: new Date().toISOString() },
        { type: "tool.call.started", commandId: "c2", threadId: "t1", occurredAt: new Date().toISOString() },
        { type: "tool.call.completed", commandId: "c3", threadId: "t1", occurredAt: new Date().toISOString(), payload: { result: "Error: sudo not allowed" } }
      )
    } as any);

    const MockEmbeddingProviderLive = Layer.succeed(EmbeddingProvider, {
      getEmbedding: (text: string) => Effect.succeed([0.1, 0.2, 0.3])
    } as any);

    // Provide a mocked SqlClient
    const MockSqlClientLive = Layer.succeed(
      SqlClient.SqlClient,
      (() => Effect.succeed([])) as any
    );

    const program = Effect.gen(function* () {
      const service = yield* HaloOptimizerService;
      yield* service.runOptimizationLoop;
    });

    const TestLayer = HaloOptimizerLive.pipe(
      Layer.provide(MockEventStoreLive),
      Layer.provide(MockEmbeddingProviderLive),
      Layer.provide(MockSqlClientLive)
    );

    await Effect.runPromise(Effect.provide(program, TestLayer));
    
    expect(global.fetch).toHaveBeenCalled();
  });
});
